name: Build and publish

on:
  push:
    branches: ['main']
    paths:
      - 'singleuser-base/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Docker Checkout
        uses: actions/checkout@v3

      - name: Log in to the GH Container Registry
        id: login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          flavor: |
            latest=true
          tags: |
            type=sha
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/singleuser-base

      - name: Build and push
        id: build
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./singleuser-base
          file: ./singleuser-base/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          